Ajusto locale por error en Windows
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\gui\controls\gridview.py", line 209, in GetTypeName
    column = self.columns[col]
  File "C:\Python27\lib\site-packages\gui\controls\gridview.py", line 149, in <lambda>
    columns = property(lambda self: self.wx_grid.obj.columns)
  File "C:\Python27\lib\site-packages\gui\controls\gridview.py", line 71, in _get_column_headings
    headers = [ctrl for ctrl in self if isinstance(ctrl, GridColumn)]
wx._core.PyAssertionError: C++ assertion "strcmp(setlocale(LC_ALL, NULL), "C") == 0" failed at ..\..\src\common\intl.cpp(1449) in wxLocale::GetInfo(): You probably called setlocale() directly instead of using wxLocale and now there is a mismatch between C/C++ and Windows locale.
Things are going to break, please only change locale by creating wxLocale objects to avoid this!